[jenkins_controller]
localhost ansible_connection=local

[jenkins_agents]
# Target Jenkins agent / EC2 instance IP or DNS
# agent1 ansible_host=18.xxx.xxx.xxx ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/devops-key.pem

[all:vars]
ansible_python_interpreter=/usr/bin/python3
