apiVersion: v1
kind: ConfigMap
metadata:
  name: streamingapp-config
  namespace: streamingapp
data:
  NODE_ENV: "production"
  AWS_REGION: "ap-south-1"
  AUTH_PORT: "3001"
  STREAMING_PORT: "3002"
  ADMIN_PORT: "3003"
  CHAT_PORT: "3004"
  CLIENT_URLS: "http://localhost:3000,http://localhost:8080,http://localhost:8081,http://a34bcc3ac9b274b18948851596d06f0b-471844516.ap-south-1.elb.amazonaws.com"
  STREAMING_PUBLIC_URL: "http://streaming-service:3002"
---
apiVersion: v1
kind: Secret
metadata:
  name: streamingapp-secrets
  namespace: streamingapp
type: Opaque
stringData:
  MONGO_URI: "mongodb://mongo:27017/streamingapp"
  JWT_SECRET: "super-secure-production-jwt-token-key-change-me"
  AWS_ACCESS_KEY_ID: "CHANGE_ME_AWS_ACCESS_KEY"
  AWS_SECRET_ACCESS_KEY: "CHANGE_ME_AWS_SECRET_KEY"
  AWS_S3_BUCKET: "streaming-app-media-bucket"
